name: 自动部署到 EdgeOne Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 部署到 EdgeOne Pages
        uses: TencentCloud/edgeone-pages-action@v1
        with:
          secret_id: ${{ secrets.TENCENT_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_SECRET_KEY }}
          zone_name: default-pages-zone
          project_name: sports-analytics
          upload_dir: ./
